name: Build Docker Image

on:
  push:
    branches:
      - '**'

env:
  REGISTRY_NAME: registry.digitalocean.com/joshnoel
  IMAGE_NAME: game

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY_NAME/$IMAGE_NAME:latest .

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push $REGISTRY_NAME/$IMAGE_NAME:latest

